<?php

namespace Database\Seeders;

use App\Models\Sentence;
use Illuminate\Database\Seeder;

class SentenceSeeder extends Seeder
{
    public function run(): void
    {
        $sentences = [
            // ========================================
            // A1 - Básico (100 frases)
            // ========================================
            ['text_pt' => 'Eu gosto de pizza.', 'text_en_reference' => 'I like pizza.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Meu nome é João.', 'text_en_reference' => 'My name is João.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Ela tem um gato.', 'text_en_reference' => 'She has a cat.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu moro no Brasil.', 'text_en_reference' => 'I live in Brazil.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Ele é meu irmão.', 'text_en_reference' => 'He is my brother.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Nós estudamos inglês.', 'text_en_reference' => 'We study English.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'O livro está na mesa.', 'text_en_reference' => 'The book is on the table.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Eu tenho fome.', 'text_en_reference' => 'I am hungry.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Hoje está sol.', 'text_en_reference' => 'It is sunny today.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eles são amigos.', 'text_en_reference' => 'They are friends.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu bebo água.', 'text_en_reference' => 'I drink water.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Ela é professora.', 'text_en_reference' => 'She is a teacher.', 'level' => 'A1', 'topic' => 'work'],
            ['text_pt' => 'Eu tenho dois irmãos.', 'text_en_reference' => 'I have two brothers.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'O carro é vermelho.', 'text_en_reference' => 'The car is red.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Nós moramos em uma casa.', 'text_en_reference' => 'We live in a house.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu como arroz e feijão.', 'text_en_reference' => 'I eat rice and beans.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Ele joga futebol.', 'text_en_reference' => 'He plays soccer.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Minha mãe cozinha bem.', 'text_en_reference' => 'My mother cooks well.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu estou feliz.', 'text_en_reference' => 'I am happy.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'O gato está dormindo.', 'text_en_reference' => 'The cat is sleeping.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu tenho vinte anos.', 'text_en_reference' => 'I am twenty years old.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Ela gosta de música.', 'text_en_reference' => 'She likes music.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'O café está quente.', 'text_en_reference' => 'The coffee is hot.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Nós somos brasileiros.', 'text_en_reference' => 'We are Brazilian.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Ele trabalha muito.', 'text_en_reference' => 'He works a lot.', 'level' => 'A1', 'topic' => 'work'],
            ['text_pt' => 'Eu tenho um cachorro.', 'text_en_reference' => 'I have a dog.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Ela mora em São Paulo.', 'text_en_reference' => 'She lives in São Paulo.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'O dia está bonito.', 'text_en_reference' => 'The day is beautiful.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu leio livros.', 'text_en_reference' => 'I read books.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Eles falam português.', 'text_en_reference' => 'They speak Portuguese.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'A escola é grande.', 'text_en_reference' => 'The school is big.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Eu gosto de frutas.', 'text_en_reference' => 'I like fruits.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Meu pai é médico.', 'text_en_reference' => 'My father is a doctor.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Nós temos aula hoje.', 'text_en_reference' => 'We have class today.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'O tempo está frio.', 'text_en_reference' => 'The weather is cold.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ela come salada.', 'text_en_reference' => 'She eats salad.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Eu durmo cedo.', 'text_en_reference' => 'I sleep early.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ele é alto.', 'text_en_reference' => 'He is tall.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu preciso de ajuda.', 'text_en_reference' => 'I need help.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'A comida está gostosa.', 'text_en_reference' => 'The food is delicious.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Eu vou ao mercado.', 'text_en_reference' => 'I go to the market.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ela escreve uma carta.', 'text_en_reference' => 'She writes a letter.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Nós gostamos de praia.', 'text_en_reference' => 'We like the beach.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'O menino está correndo.', 'text_en_reference' => 'The boy is running.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu assisto televisão.', 'text_en_reference' => 'I watch television.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele estuda à noite.', 'text_en_reference' => 'He studies at night.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Minha casa é pequena.', 'text_en_reference' => 'My house is small.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu tomo café da manhã.', 'text_en_reference' => 'I have breakfast.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Ela usa óculos.', 'text_en_reference' => 'She wears glasses.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'O parque é bonito.', 'text_en_reference' => 'The park is beautiful.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Eu compro pão.', 'text_en_reference' => 'I buy bread.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Nós caminhamos no parque.', 'text_en_reference' => 'We walk in the park.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'O ônibus está atrasado.', 'text_en_reference' => 'The bus is late.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Ela tem cabelo longo.', 'text_en_reference' => 'She has long hair.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu ouço música.', 'text_en_reference' => 'I listen to music.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele toma banho de manhã.', 'text_en_reference' => 'He takes a shower in the morning.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'A loja está fechada.', 'text_en_reference' => 'The store is closed.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu faço exercícios.', 'text_en_reference' => 'I exercise.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ela tem olhos azuis.', 'text_en_reference' => 'She has blue eyes.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Meu amigo mora perto.', 'text_en_reference' => 'My friend lives nearby.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu gosto de chocolate.', 'text_en_reference' => 'I like chocolate.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Nós temos um jardim.', 'text_en_reference' => 'We have a garden.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'O filme é bom.', 'text_en_reference' => 'The movie is good.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele come banana.', 'text_en_reference' => 'He eats a banana.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Eu abro a janela.', 'text_en_reference' => 'I open the window.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ela dança bem.', 'text_en_reference' => 'She dances well.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'O bebê está chorando.', 'text_en_reference' => 'The baby is crying.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Eu lavo as mãos.', 'text_en_reference' => 'I wash my hands.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Nós vamos à escola.', 'text_en_reference' => 'We go to school.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Ele dirige um carro.', 'text_en_reference' => 'He drives a car.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'A porta está aberta.', 'text_en_reference' => 'The door is open.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu conheço essa pessoa.', 'text_en_reference' => 'I know this person.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Ela corre todo dia.', 'text_en_reference' => 'She runs every day.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'O supermercado é perto.', 'text_en_reference' => 'The supermarket is nearby.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu uso o computador.', 'text_en_reference' => 'I use the computer.', 'level' => 'A1', 'topic' => 'work'],
            ['text_pt' => 'Ela quer sorvete.', 'text_en_reference' => 'She wants ice cream.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Nós ouvimos o professor.', 'text_en_reference' => 'We listen to the teacher.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'O hospital é longe.', 'text_en_reference' => 'The hospital is far.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Eu limpo a casa.', 'text_en_reference' => 'I clean the house.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ele desenha muito bem.', 'text_en_reference' => 'He draws very well.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'A rua é larga.', 'text_en_reference' => 'The street is wide.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Eu espero o ônibus.', 'text_en_reference' => 'I wait for the bus.', 'level' => 'A1', 'topic' => 'travel'],
            ['text_pt' => 'Ela canta no chuveiro.', 'text_en_reference' => 'She sings in the shower.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'O céu está azul.', 'text_en_reference' => 'The sky is blue.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu pago a conta.', 'text_en_reference' => 'I pay the bill.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Nós jogamos cartas.', 'text_en_reference' => 'We play cards.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele dorme no sofá.', 'text_en_reference' => 'He sleeps on the sofa.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'A flor é vermelha.', 'text_en_reference' => 'The flower is red.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu fecho a porta.', 'text_en_reference' => 'I close the door.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Ela lê um livro.', 'text_en_reference' => 'She reads a book.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'O pássaro está voando.', 'text_en_reference' => 'The bird is flying.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu moro com minha família.', 'text_en_reference' => 'I live with my family.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'Nós comemos juntos.', 'text_en_reference' => 'We eat together.', 'level' => 'A1', 'topic' => 'family'],
            ['text_pt' => 'O relógio está quebrado.', 'text_en_reference' => 'The clock is broken.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Eu tenho sede.', 'text_en_reference' => 'I am thirsty.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Ela ensina matemática.', 'text_en_reference' => 'She teaches math.', 'level' => 'A1', 'topic' => 'education'],
            ['text_pt' => 'Ele nada na piscina.', 'text_en_reference' => 'He swims in the pool.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'O jantar está pronto.', 'text_en_reference' => 'Dinner is ready.', 'level' => 'A1', 'topic' => 'food'],
            ['text_pt' => 'Eu tenho sono.', 'text_en_reference' => 'I am sleepy.', 'level' => 'A1', 'topic' => 'routine'],
            ['text_pt' => 'Nós brincamos no quintal.', 'text_en_reference' => 'We play in the backyard.', 'level' => 'A1', 'topic' => 'entertainment'],
            ['text_pt' => 'A água está fria.', 'text_en_reference' => 'The water is cold.', 'level' => 'A1', 'topic' => 'food'],

            // ========================================
            // A2 - Elementar (100 frases)
            // ========================================
            ['text_pt' => 'Eu vou à escola todos os dias.', 'text_en_reference' => 'I go to school every day.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela está cozinhando o jantar.', 'text_en_reference' => 'She is cooking dinner.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Nós visitamos meus avós no fim de semana.', 'text_en_reference' => 'We visit my grandparents on the weekend.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Eu gostaria de um café, por favor.', 'text_en_reference' => 'I would like a coffee, please.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ele trabalha em uma empresa grande.', 'text_en_reference' => 'He works at a big company.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Eles estão planejando uma viagem.', 'text_en_reference' => 'They are planning a trip.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Eu acordo às sete horas.', 'text_en_reference' => 'I wake up at seven o\'clock.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela está aprendendo a dirigir.', 'text_en_reference' => 'She is learning to drive.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Nós gostamos de assistir filmes.', 'text_en_reference' => 'We like watching movies.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'O restaurante abre às onze.', 'text_en_reference' => 'The restaurant opens at eleven.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Eu fui ao cinema ontem.', 'text_en_reference' => 'I went to the cinema yesterday.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Ela comprou um vestido novo.', 'text_en_reference' => 'She bought a new dress.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Nós tomamos café da manhã às oito.', 'text_en_reference' => 'We have breakfast at eight.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ele precisa ir ao dentista.', 'text_en_reference' => 'He needs to go to the dentist.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu estou procurando um emprego.', 'text_en_reference' => 'I am looking for a job.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Ela viajou para a Europa no ano passado.', 'text_en_reference' => 'She traveled to Europe last year.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Nós sempre jantamos às sete.', 'text_en_reference' => 'We always have dinner at seven.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ele está lendo um jornal.', 'text_en_reference' => 'He is reading a newspaper.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu preciso comprar leite.', 'text_en_reference' => 'I need to buy milk.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ela trabalha de segunda a sexta.', 'text_en_reference' => 'She works from Monday to Friday.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'O hotel fica perto da praia.', 'text_en_reference' => 'The hotel is near the beach.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Eu estudo inglês duas vezes por semana.', 'text_en_reference' => 'I study English twice a week.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Ela esqueceu as chaves em casa.', 'text_en_reference' => 'She forgot her keys at home.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Nós fomos ao parque ontem.', 'text_en_reference' => 'We went to the park yesterday.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele está esperando o taxi.', 'text_en_reference' => 'He is waiting for the taxi.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Eu não gosto de acordar cedo.', 'text_en_reference' => 'I don\'t like waking up early.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela mora sozinha.', 'text_en_reference' => 'She lives alone.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Nós temos que sair agora.', 'text_en_reference' => 'We have to leave now.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ele perdeu o voo.', 'text_en_reference' => 'He missed the flight.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Eu quero aprender a cozinhar.', 'text_en_reference' => 'I want to learn to cook.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ela está falando ao telefone.', 'text_en_reference' => 'She is talking on the phone.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Nós mudamos de casa mês passado.', 'text_en_reference' => 'We moved house last month.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Ele sempre chega atrasado.', 'text_en_reference' => 'He always arrives late.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Eu terminei minha lição de casa.', 'text_en_reference' => 'I finished my homework.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Ela tem medo de avião.', 'text_en_reference' => 'She is afraid of flying.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Nós jogamos vôlei na praia.', 'text_en_reference' => 'We played volleyball at the beach.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele convidou os amigos para o churrasco.', 'text_en_reference' => 'He invited his friends to the barbecue.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Eu preciso trocar dinheiro.', 'text_en_reference' => 'I need to exchange money.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ela quer ser enfermeira.', 'text_en_reference' => 'She wants to be a nurse.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Nós almoçamos fora hoje.', 'text_en_reference' => 'We had lunch out today.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ele está usando uma camisa azul.', 'text_en_reference' => 'He is wearing a blue shirt.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu gosto mais de verão do que inverno.', 'text_en_reference' => 'I like summer more than winter.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela pediu a conta no restaurante.', 'text_en_reference' => 'She asked for the bill at the restaurant.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Nós encontramos um bom hotel.', 'text_en_reference' => 'We found a good hotel.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ele estuda para ser engenheiro.', 'text_en_reference' => 'He studies to be an engineer.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Eu costumo correr de manhã.', 'text_en_reference' => 'I usually run in the morning.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela fez um bolo de chocolate.', 'text_en_reference' => 'She made a chocolate cake.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Nós assistimos ao jogo juntos.', 'text_en_reference' => 'We watched the game together.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Ele não consegue dormir.', 'text_en_reference' => 'He can\'t sleep.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu vou viajar no Natal.', 'text_en_reference' => 'I am going to travel at Christmas.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ela está esperando um bebê.', 'text_en_reference' => 'She is expecting a baby.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Nós compramos uma casa nova.', 'text_en_reference' => 'We bought a new house.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Ele precisa de óculos novos.', 'text_en_reference' => 'He needs new glasses.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu conheci meu vizinho ontem.', 'text_en_reference' => 'I met my neighbor yesterday.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Ela vai começar um novo emprego.', 'text_en_reference' => 'She is going to start a new job.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Nós perdemos o trem.', 'text_en_reference' => 'We missed the train.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ele cozinhou para a família.', 'text_en_reference' => 'He cooked for the family.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Eu vou ao médico amanhã.', 'text_en_reference' => 'I am going to the doctor tomorrow.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela está estudando para a prova.', 'text_en_reference' => 'She is studying for the test.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Nós saímos para jantar.', 'text_en_reference' => 'We went out for dinner.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ele mandou uma mensagem para ela.', 'text_en_reference' => 'He sent her a message.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu preciso praticar mais.', 'text_en_reference' => 'I need to practice more.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Ela ganhou um presente de aniversário.', 'text_en_reference' => 'She got a birthday present.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Nós reservamos um quarto de hotel.', 'text_en_reference' => 'We booked a hotel room.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ele quer aprender a tocar violão.', 'text_en_reference' => 'He wants to learn to play guitar.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu fiz compras no shopping.', 'text_en_reference' => 'I went shopping at the mall.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela corre no parque toda manhã.', 'text_en_reference' => 'She runs in the park every morning.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Nós estamos atrasados para a aula.', 'text_en_reference' => 'We are late for class.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Ele consertar o chuveiro.', 'text_en_reference' => 'He fixed the shower.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu passei na prova.', 'text_en_reference' => 'I passed the test.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Ela trouxe o almoço de casa.', 'text_en_reference' => 'She brought lunch from home.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Nós cantamos parabéns para ele.', 'text_en_reference' => 'We sang happy birthday to him.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Ele vai cortar o cabelo.', 'text_en_reference' => 'He is going to get a haircut.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Eu estou com dor de cabeça.', 'text_en_reference' => 'I have a headache.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela sabe falar três idiomas.', 'text_en_reference' => 'She can speak three languages.', 'level' => 'A2', 'topic' => 'education'],
            ['text_pt' => 'Nós vamos à praia no verão.', 'text_en_reference' => 'We go to the beach in the summer.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ele gosta de ouvir podcast.', 'text_en_reference' => 'He likes listening to podcasts.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu esqueci de pagar a conta.', 'text_en_reference' => 'I forgot to pay the bill.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela está organizando a festa.', 'text_en_reference' => 'She is organizing the party.', 'level' => 'A2', 'topic' => 'entertainment'],
            ['text_pt' => 'Nós devemos chegar antes das dez.', 'text_en_reference' => 'We should arrive before ten.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ele está procurando o passaporte.', 'text_en_reference' => 'He is looking for his passport.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Eu gosto de caminhar na chuva.', 'text_en_reference' => 'I like walking in the rain.', 'level' => 'A2', 'topic' => 'routine'],
            ['text_pt' => 'Ela quer mudar de carreira.', 'text_en_reference' => 'She wants to change careers.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Nós fizemos uma torta de maçã.', 'text_en_reference' => 'We made an apple pie.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ele ligou para os pais dele.', 'text_en_reference' => 'He called his parents.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Eu prefiro chá a café.', 'text_en_reference' => 'I prefer tea to coffee.', 'level' => 'A2', 'topic' => 'food'],
            ['text_pt' => 'Ela leva as crianças para a escola.', 'text_en_reference' => 'She takes the kids to school.', 'level' => 'A2', 'topic' => 'family'],
            ['text_pt' => 'Nós estamos economizando para viajar.', 'text_en_reference' => 'We are saving to travel.', 'level' => 'A2', 'topic' => 'travel'],
            ['text_pt' => 'Ele conseguiu uma promoção.', 'text_en_reference' => 'He got a promotion.', 'level' => 'A2', 'topic' => 'work'],
            ['text_pt' => 'Eu preciso renovar meu passaporte.', 'text_en_reference' => 'I need to renew my passport.', 'level' => 'A2', 'topic' => 'travel'],

            // ========================================
            // B1 - Intermediário (100 frases)
            // ========================================
            ['text_pt' => 'Eu tenho estudado inglês há três anos.', 'text_en_reference' => 'I have been studying English for three years.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Se eu tivesse mais tempo, viajaria mais.', 'text_en_reference' => 'If I had more time, I would travel more.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ela disse que viria à festa.', 'text_en_reference' => 'She said she would come to the party.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu estava dormindo quando você ligou.', 'text_en_reference' => 'I was sleeping when you called.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Eles têm morado aqui desde 2020.', 'text_en_reference' => 'They have been living here since 2020.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Eu gostaria de saber mais sobre isso.', 'text_en_reference' => 'I would like to know more about it.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Ela deve estar no trabalho agora.', 'text_en_reference' => 'She must be at work now.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós poderíamos tentar uma solução diferente.', 'text_en_reference' => 'We could try a different solution.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ele ficou surpreso com a notícia.', 'text_en_reference' => 'He was surprised by the news.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Eu prefiro café a chá.', 'text_en_reference' => 'I prefer coffee to tea.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Quando eu era criança, brincava na rua.', 'text_en_reference' => 'When I was a child, I used to play in the street.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Se chover, ficaremos em casa.', 'text_en_reference' => 'If it rains, we will stay at home.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ele me pediu para ajudá-lo.', 'text_en_reference' => 'He asked me to help him.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu nunca tinha visto neve antes.', 'text_en_reference' => 'I had never seen snow before.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ela está pensando em mudar de emprego.', 'text_en_reference' => 'She is thinking about changing jobs.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós deveríamos ter saído mais cedo.', 'text_en_reference' => 'We should have left earlier.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ele me contou que vai se casar.', 'text_en_reference' => 'He told me he is going to get married.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Eu estou acostumado a acordar cedo.', 'text_en_reference' => 'I am used to waking up early.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ela já tinha terminado quando eu cheguei.', 'text_en_reference' => 'She had already finished when I arrived.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Nós precisamos resolver esse problema.', 'text_en_reference' => 'We need to solve this problem.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ele não deveria ter dito isso.', 'text_en_reference' => 'He shouldn\'t have said that.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Eu costumava jogar tênis quando jovem.', 'text_en_reference' => 'I used to play tennis when I was young.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ela pode estar ocupada agora.', 'text_en_reference' => 'She might be busy right now.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'O filme foi dirigido por um brasileiro.', 'text_en_reference' => 'The movie was directed by a Brazilian.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu tenho me sentido cansado ultimamente.', 'text_en_reference' => 'I have been feeling tired lately.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Se eu fosse você, aceitaria a oferta.', 'text_en_reference' => 'If I were you, I would accept the offer.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós ainda não decidimos para onde ir.', 'text_en_reference' => 'We haven\'t decided where to go yet.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele está tentando economizar dinheiro.', 'text_en_reference' => 'He is trying to save money.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu acho que vai chover amanhã.', 'text_en_reference' => 'I think it is going to rain tomorrow.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ela me perguntou se eu podia ajudar.', 'text_en_reference' => 'She asked me if I could help.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Nós estávamos cozinhando quando a luz acabou.', 'text_en_reference' => 'We were cooking when the power went out.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Ele prometeu que voltaria cedo.', 'text_en_reference' => 'He promised he would come back early.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Eu tenho que entregar o relatório até sexta.', 'text_en_reference' => 'I have to submit the report by Friday.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ela pode ter esquecido do compromisso.', 'text_en_reference' => 'She may have forgotten about the appointment.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Nós gastamos mais do que planejamos.', 'text_en_reference' => 'We spent more than we planned.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Se eu soubesse a resposta, te diria.', 'text_en_reference' => 'If I knew the answer, I would tell you.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Ele disse que estava estudando.', 'text_en_reference' => 'He said he was studying.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Eu tenho praticado piano todos os dias.', 'text_en_reference' => 'I have been practicing piano every day.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ela se recusou a ir à reunião.', 'text_en_reference' => 'She refused to go to the meeting.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós vamos precisar de mais tempo.', 'text_en_reference' => 'We are going to need more time.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ele conseguiu resolver o problema sozinho.', 'text_en_reference' => 'He managed to solve the problem by himself.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu espero que você tenha uma boa viagem.', 'text_en_reference' => 'I hope you have a good trip.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ela parece estar mais feliz agora.', 'text_en_reference' => 'She seems to be happier now.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Nós decidimos adiar a viagem.', 'text_en_reference' => 'We decided to postpone the trip.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele sugeriu que fôssemos ao cinema.', 'text_en_reference' => 'He suggested that we go to the cinema.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu deveria ter estudado mais.', 'text_en_reference' => 'I should have studied more.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Ela está tentando encontrar um apartamento.', 'text_en_reference' => 'She is trying to find an apartment.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Nós ainda não nos acostumamos com o fuso.', 'text_en_reference' => 'We haven\'t gotten used to the time zone yet.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele foi promovido no mês passado.', 'text_en_reference' => 'He was promoted last month.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu gostaria de ter aprendido antes.', 'text_en_reference' => 'I wish I had learned earlier.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Ela me convidou para jantar.', 'text_en_reference' => 'She invited me to dinner.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Nós não conseguimos encontrar o endereço.', 'text_en_reference' => 'We couldn\'t find the address.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele está se preparando para uma entrevista.', 'text_en_reference' => 'He is preparing for an interview.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu me arrependo de não ter ido.', 'text_en_reference' => 'I regret not going.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ela faz aniversário na próxima semana.', 'text_en_reference' => 'Her birthday is next week.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Nós não sabíamos que era tão longe.', 'text_en_reference' => 'We didn\'t know it was so far.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele me ensinou a cozinhar esse prato.', 'text_en_reference' => 'He taught me how to cook this dish.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Eu tenho trabalhado remotamente desde março.', 'text_en_reference' => 'I have been working remotely since March.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ela explicou por que não veio.', 'text_en_reference' => 'She explained why she didn\'t come.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Nós gostaríamos de experimentar a comida local.', 'text_en_reference' => 'We would like to try the local food.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Quanto tempo faz que você mora aqui?', 'text_en_reference' => 'How long have you lived here?', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Eu não conseguia parar de rir.', 'text_en_reference' => 'I couldn\'t stop laughing.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Ela se ofereceu para nos ajudar.', 'text_en_reference' => 'She offered to help us.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós temos que estar lá às oito em ponto.', 'text_en_reference' => 'We have to be there at eight sharp.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ele concordou em adiar a reunião.', 'text_en_reference' => 'He agreed to postpone the meeting.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Eu estava prestes a sair quando começou a chover.', 'text_en_reference' => 'I was about to leave when it started raining.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ela está ansiosa para conhecer o país.', 'text_en_reference' => 'She is eager to visit the country.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Nós quase perdemos o voo.', 'text_en_reference' => 'We almost missed the flight.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Ele evita comer doces.', 'text_en_reference' => 'He avoids eating sweets.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Eu pretendo me formar ano que vem.', 'text_en_reference' => 'I plan to graduate next year.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Ela acabou de voltar de férias.', 'text_en_reference' => 'She just came back from vacation.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Nós estamos considerando contratar alguém.', 'text_en_reference' => 'We are considering hiring someone.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ele não parece estar interessado.', 'text_en_reference' => 'He doesn\'t seem to be interested.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Eu tive sorte de encontrar essa oportunidade.', 'text_en_reference' => 'I was lucky to find this opportunity.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ela fez questão de agradecer a todos.', 'text_en_reference' => 'She made a point of thanking everyone.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Nós não sabemos quando ele vai chegar.', 'text_en_reference' => 'We don\'t know when he is going to arrive.', 'level' => 'B1', 'topic' => 'travel'],
            ['text_pt' => 'Se eu tivesse dinheiro, compraria um carro.', 'text_en_reference' => 'If I had money, I would buy a car.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Ela me disse que já tinha almoçado.', 'text_en_reference' => 'She told me she had already had lunch.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Eu tenho vontade de aprender francês.', 'text_en_reference' => 'I feel like learning French.', 'level' => 'B1', 'topic' => 'education'],
            ['text_pt' => 'Nós acabamos de nos mudar para cá.', 'text_en_reference' => 'We have just moved here.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Ele deixou de fumar há dois anos.', 'text_en_reference' => 'He quit smoking two years ago.', 'level' => 'B1', 'topic' => 'routine'],
            ['text_pt' => 'Eu nunca esquecerei desse dia.', 'text_en_reference' => 'I will never forget this day.', 'level' => 'B1', 'topic' => 'family'],
            ['text_pt' => 'Ela está tão animada quanto eu.', 'text_en_reference' => 'She is as excited as I am.', 'level' => 'B1', 'topic' => 'entertainment'],
            ['text_pt' => 'Nós precisamos terminar antes do prazo.', 'text_en_reference' => 'We need to finish before the deadline.', 'level' => 'B1', 'topic' => 'work'],
            ['text_pt' => 'Ele insistiu em pagar a conta.', 'text_en_reference' => 'He insisted on paying the bill.', 'level' => 'B1', 'topic' => 'food'],
            ['text_pt' => 'Quanto mais eu leio, mais eu aprendo.', 'text_en_reference' => 'The more I read, the more I learn.', 'level' => 'B1', 'topic' => 'education'],

            // ========================================
            // B2 - Intermediário Superior (100 frases)
            // ========================================
            ['text_pt' => 'Apesar de estar chovendo, decidimos sair.', 'text_en_reference' => 'Despite it raining, we decided to go out.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Ele deveria ter estudado mais para a prova.', 'text_en_reference' => 'He should have studied more for the test.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Não só ela canta bem, como também toca piano.', 'text_en_reference' => 'Not only does she sing well, but she also plays piano.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'Caso você precise de ajuda, me avise.', 'text_en_reference' => 'In case you need help, let me know.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Quanto mais eu pratico, melhor eu fico.', 'text_en_reference' => 'The more I practice, the better I get.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Ela teria vindo se soubesse da reunião.', 'text_en_reference' => 'She would have come if she had known about the meeting.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'É provável que eles cheguem atrasados.', 'text_en_reference' => 'They are likely to arrive late.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Eu estava prestes a sair quando o telefone tocou.', 'text_en_reference' => 'I was about to leave when the phone rang.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Mal começamos o projeto e já encontramos problemas.', 'text_en_reference' => 'No sooner had we started the project than we found problems.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ela age como se fosse a chefe.', 'text_en_reference' => 'She acts as if she were the boss.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Por mais que tentemos, não conseguimos resolver.', 'text_en_reference' => 'No matter how hard we try, we can\'t solve it.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'A proposta foi rejeitada pela diretoria.', 'text_en_reference' => 'The proposal was rejected by the board.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ele acabou admitindo que estava errado.', 'text_en_reference' => 'He ended up admitting he was wrong.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Tanto eu quanto ela estávamos cansados.', 'text_en_reference' => 'Both she and I were tired.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'A menos que chova, o evento será ao ar livre.', 'text_en_reference' => 'Unless it rains, the event will be outdoors.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu tenho me dedicado bastante a esse projeto.', 'text_en_reference' => 'I have been quite dedicated to this project.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ela relutou em aceitar a mudança.', 'text_en_reference' => 'She was reluctant to accept the change.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Não fazia ideia de que seria tão complicado.', 'text_en_reference' => 'I had no idea it would be so complicated.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Ele nos convenceu a participar do evento.', 'text_en_reference' => 'He convinced us to attend the event.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'A reunião foi adiada para a próxima semana.', 'text_en_reference' => 'The meeting was postponed until next week.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ainda que eu discorde, respeito sua opinião.', 'text_en_reference' => 'Even though I disagree, I respect your opinion.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'O relatório precisa ser entregue até amanhã.', 'text_en_reference' => 'The report needs to be submitted by tomorrow.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Se não fosse pelo trânsito, teríamos chegado a tempo.', 'text_en_reference' => 'If it weren\'t for the traffic, we would have arrived on time.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Ela estava tão ocupada que nem almoçou.', 'text_en_reference' => 'She was so busy that she didn\'t even have lunch.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Parece que vai haver uma mudança de planos.', 'text_en_reference' => 'It seems like there is going to be a change of plans.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Eu teria gostado de ter ido à festa.', 'text_en_reference' => 'I would have liked to have gone to the party.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'A não ser que ele mude de ideia, o projeto vai atrasar.', 'text_en_reference' => 'Unless he changes his mind, the project will be delayed.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Por causa da greve, os voos foram cancelados.', 'text_en_reference' => 'Due to the strike, the flights were cancelled.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Ele se comportou como se nada tivesse acontecido.', 'text_en_reference' => 'He behaved as if nothing had happened.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'É essencial que terminemos esse trabalho hoje.', 'text_en_reference' => 'It is essential that we finish this work today.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Supondo que ele aceite, quando começamos?', 'text_en_reference' => 'Assuming he accepts, when do we start?', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'A comida estava tão boa que pedimos mais.', 'text_en_reference' => 'The food was so good that we ordered more.', 'level' => 'B2', 'topic' => 'food'],
            ['text_pt' => 'Ele está longe de ser o melhor candidato.', 'text_en_reference' => 'He is far from being the best candidate.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Fomos informados de que o prazo mudou.', 'text_en_reference' => 'We were informed that the deadline had changed.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Embora tenha chovido, o show foi um sucesso.', 'text_en_reference' => 'Although it rained, the show was a success.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'Não vale a pena discutir sobre isso.', 'text_en_reference' => 'It is not worth arguing about this.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Ela levou uma hora para chegar ao aeroporto.', 'text_en_reference' => 'It took her an hour to get to the airport.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Eles nos pediram para manter segredo.', 'text_en_reference' => 'They asked us to keep it a secret.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Desde que comecei a ler mais, meu vocabulário melhorou.', 'text_en_reference' => 'Since I started reading more, my vocabulary has improved.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Ele tem tendência a exagerar.', 'text_en_reference' => 'He tends to exaggerate.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Nós estamos no meio de uma negociação.', 'text_en_reference' => 'We are in the middle of a negotiation.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Se tivéssemos saído mais cedo, teríamos evitado o trânsito.', 'text_en_reference' => 'If we had left earlier, we would have avoided the traffic.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Ela se recusou a fazer horas extras.', 'text_en_reference' => 'She refused to work overtime.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Eu duvido que ele saiba a verdade.', 'text_en_reference' => 'I doubt he knows the truth.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'A empresa está passando por dificuldades financeiras.', 'text_en_reference' => 'The company is going through financial difficulties.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Eu nunca me acostumei a trabalhar à noite.', 'text_en_reference' => 'I never got used to working at night.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ela faz questão de almoçar com a família aos domingos.', 'text_en_reference' => 'She makes a point of having lunch with the family on Sundays.', 'level' => 'B2', 'topic' => 'family'],
            ['text_pt' => 'A primeira coisa que notei foi a arquitetura.', 'text_en_reference' => 'The first thing I noticed was the architecture.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Desde que ele se formou, tem trabalhado na mesma empresa.', 'text_en_reference' => 'Since he graduated, he has been working at the same company.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Por mais caro que seja, eu vou comprar.', 'text_en_reference' => 'No matter how expensive it is, I am going to buy it.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Não havia ninguém no escritório quando cheguei.', 'text_en_reference' => 'There was nobody at the office when I arrived.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Eles investiram uma fortuna naquele negócio.', 'text_en_reference' => 'They invested a fortune in that business.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Eu teria viajado se tivesse férias.', 'text_en_reference' => 'I would have traveled if I had had vacation.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'O resultado ficou além das nossas expectativas.', 'text_en_reference' => 'The result exceeded our expectations.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ela está acostumada a lidar com clientes difíceis.', 'text_en_reference' => 'She is used to dealing with difficult clients.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Nenhum de nós sabia o que fazer.', 'text_en_reference' => 'None of us knew what to do.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Eu mal posso esperar para as férias.', 'text_en_reference' => 'I can hardly wait for the holidays.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Seja qual for a decisão, eu aceito.', 'text_en_reference' => 'Whatever the decision may be, I accept it.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Ele nos aconselhou a não investir naquilo.', 'text_en_reference' => 'He advised us not to invest in that.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Quanto mais eu penso nisso, mais confuso fico.', 'text_en_reference' => 'The more I think about it, the more confused I get.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'A experiência no exterior me fez crescer muito.', 'text_en_reference' => 'The experience abroad made me grow a lot.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Ela não só terminou o curso como também conseguiu emprego.', 'text_en_reference' => 'She not only finished the course but also got a job.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Está na hora de tomarmos uma decisão.', 'text_en_reference' => 'It is time for us to make a decision.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ele afirmou que não sabia de nada.', 'text_en_reference' => 'He claimed that he didn\'t know anything.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Por falta de tempo, não conseguimos terminar.', 'text_en_reference' => 'Due to lack of time, we couldn\'t finish.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'A pesquisa revela que o problema é maior do que imaginamos.', 'text_en_reference' => 'The research reveals that the problem is bigger than we thought.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Eu gostaria que as coisas fossem diferentes.', 'text_en_reference' => 'I wish things were different.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'Ao contrário do que esperávamos, ele aceitou.', 'text_en_reference' => 'Contrary to what we expected, he accepted.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Ela acabou desistindo do curso.', 'text_en_reference' => 'She ended up dropping out of the course.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'A viagem valeu cada centavo.', 'text_en_reference' => 'The trip was worth every penny.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'Considerando as circunstâncias, fizemos um bom trabalho.', 'text_en_reference' => 'Considering the circumstances, we did a good job.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Não há como saber o resultado antes da hora.', 'text_en_reference' => 'There is no way to know the result beforehand.', 'level' => 'B2', 'topic' => 'routine'],
            ['text_pt' => 'O festival atraiu pessoas de todo o país.', 'text_en_reference' => 'The festival attracted people from all over the country.', 'level' => 'B2', 'topic' => 'entertainment'],
            ['text_pt' => 'Eu nunca tinha comido algo tão bom.', 'text_en_reference' => 'I had never eaten anything so good.', 'level' => 'B2', 'topic' => 'food'],
            ['text_pt' => 'Ela tem facilidade para aprender idiomas.', 'text_en_reference' => 'She has a talent for learning languages.', 'level' => 'B2', 'topic' => 'education'],
            ['text_pt' => 'Ele prometeu que nos manteria informados.', 'text_en_reference' => 'He promised he would keep us informed.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Nós tivemos que nos adaptar rapidamente.', 'text_en_reference' => 'We had to adapt quickly.', 'level' => 'B2', 'topic' => 'work'],
            ['text_pt' => 'Mesmo depois de tantos anos, ele ainda se lembra.', 'text_en_reference' => 'Even after so many years, he still remembers.', 'level' => 'B2', 'topic' => 'family'],
            ['text_pt' => 'Supõe-se que ele chegue ao meio-dia.', 'text_en_reference' => 'He is supposed to arrive at noon.', 'level' => 'B2', 'topic' => 'travel'],
            ['text_pt' => 'A decisão depende de vários fatores.', 'text_en_reference' => 'The decision depends on several factors.', 'level' => 'B2', 'topic' => 'work'],

            // ========================================
            // C1 - Avançado (100 frases)
            // ========================================
            ['text_pt' => 'Raramente tenho visto uma apresentação tão impressionante.', 'text_en_reference' => 'Rarely have I seen such an impressive presentation.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Caso tivesse sabido das consequências, teria agido diferente.', 'text_en_reference' => 'Had I known the consequences, I would have acted differently.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Não há como negar que a situação é complexa.', 'text_en_reference' => 'There is no denying that the situation is complex.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Dificilmente encontraremos uma solução perfeita.', 'text_en_reference' => 'We will hardly find a perfect solution.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ele se acostumou a trabalhar sob pressão.', 'text_en_reference' => 'He has gotten used to working under pressure.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Embora seja difícil, vale a pena tentar.', 'text_en_reference' => 'Although it is difficult, it is worth trying.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Não fosse pela sua ajuda, eu teria falhado.', 'text_en_reference' => 'Were it not for your help, I would have failed.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'É fundamental que todos entendam as regras.', 'text_en_reference' => 'It is essential that everyone understand the rules.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ela fez questão de esclarecer todos os pontos.', 'text_en_reference' => 'She made a point of clarifying all the points.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Por mais que eu tente, não consigo entender.', 'text_en_reference' => 'No matter how hard I try, I cannot understand.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Em hipótese alguma devemos desistir agora.', 'text_en_reference' => 'Under no circumstances should we give up now.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Somente após muita reflexão ele tomou a decisão.', 'text_en_reference' => 'Only after much reflection did he make the decision.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Ela alegou ter sido mal interpretada.', 'text_en_reference' => 'She claimed to have been misunderstood.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'É imprescindível que o contrato seja revisado.', 'text_en_reference' => 'It is imperative that the contract be reviewed.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Mal ele terminou de falar, todos aplaudiram.', 'text_en_reference' => 'No sooner had he finished speaking than everyone applauded.', 'level' => 'C1', 'topic' => 'entertainment'],
            ['text_pt' => 'Tendo em vista a complexidade do caso, precisamos de mais tempo.', 'text_en_reference' => 'Given the complexity of the case, we need more time.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ele nunca havia enfrentado tamanho desafio.', 'text_en_reference' => 'He had never faced such a challenge.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Independentemente do resultado, aprendemos muito.', 'text_en_reference' => 'Regardless of the outcome, we learned a lot.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'A proposta, embora ambiciosa, é viável.', 'text_en_reference' => 'The proposal, although ambitious, is feasible.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Jamais imaginei que chegaria a esse ponto.', 'text_en_reference' => 'Never did I imagine I would reach this point.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Ele fez com que todos se sentissem à vontade.', 'text_en_reference' => 'He made everyone feel at ease.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'O problema reside na falta de comunicação.', 'text_en_reference' => 'The problem lies in the lack of communication.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'É preciso que nos adaptemos às mudanças.', 'text_en_reference' => 'It is necessary that we adapt to the changes.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Não fosse a intervenção dele, a situação teria piorado.', 'text_en_reference' => 'Had it not been for his intervention, the situation would have worsened.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ela demonstrou uma capacidade excepcional de liderança.', 'text_en_reference' => 'She demonstrated an exceptional leadership ability.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Só quando perdi é que percebi o valor.', 'text_en_reference' => 'Only when I lost it did I realize its value.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'A julgar pelos resultados, a estratégia funcionou.', 'text_en_reference' => 'Judging by the results, the strategy worked.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ainda que pareça impossível, devemos tentar.', 'text_en_reference' => 'Even if it seems impossible, we should try.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ele veio a ser um dos maiores especialistas da área.', 'text_en_reference' => 'He went on to become one of the greatest experts in the field.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Convém ressaltar que os dados são preliminares.', 'text_en_reference' => 'It is worth noting that the data is preliminary.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Não há por que se preocupar com isso agora.', 'text_en_reference' => 'There is no reason to worry about this now.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'A experiência, por mais dolorosa que seja, nos ensina.', 'text_en_reference' => 'Experience, no matter how painful, teaches us.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Cabe ao governo tomar as medidas necessárias.', 'text_en_reference' => 'It is up to the government to take the necessary measures.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ele deu a entender que não concordava.', 'text_en_reference' => 'He implied that he did not agree.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Em momento algum ele demonstrou fraqueza.', 'text_en_reference' => 'At no point did he show weakness.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A pesquisa aponta para uma tendência preocupante.', 'text_en_reference' => 'The research points to a worrying trend.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'O fato de ele ter vindo já é um bom sinal.', 'text_en_reference' => 'The fact that he came is already a good sign.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Via de regra, as decisões são tomadas em consenso.', 'text_en_reference' => 'As a rule, decisions are made by consensus.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Trata-se de uma questão de extrema importância.', 'text_en_reference' => 'It is a matter of utmost importance.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Muito embora discordássemos, mantivemos o respeito.', 'text_en_reference' => 'Even though we disagreed, we maintained respect.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Ao que tudo indica, o mercado vai se recuperar.', 'text_en_reference' => 'All signs point to the market recovering.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A questão levantada merece uma análise mais aprofundada.', 'text_en_reference' => 'The issue raised deserves a more thorough analysis.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ele se dispôs a assumir toda a responsabilidade.', 'text_en_reference' => 'He was willing to take on full responsibility.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Não obstante as dificuldades, o projeto avançou.', 'text_en_reference' => 'Notwithstanding the difficulties, the project moved forward.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'É necessário que haja mais transparência nas decisões.', 'text_en_reference' => 'There needs to be more transparency in the decisions.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ela se viu obrigada a reconsiderar sua posição.', 'text_en_reference' => 'She found herself forced to reconsider her position.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Nenhuma das alternativas propostas é satisfatória.', 'text_en_reference' => 'None of the proposed alternatives is satisfactory.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Faz-se necessária uma abordagem mais cautelosa.', 'text_en_reference' => 'A more cautious approach is necessary.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A despeito das críticas, ele manteve sua posição.', 'text_en_reference' => 'Despite the criticism, he maintained his position.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Quer queiramos quer não, a mudança é inevitável.', 'text_en_reference' => 'Whether we like it or not, change is inevitable.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'A conferência proporcionou insights valiosos.', 'text_en_reference' => 'The conference provided valuable insights.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'O sucesso do projeto deve-se ao trabalho em equipe.', 'text_en_reference' => 'The success of the project is due to teamwork.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Seria ingênuo acreditar que isso não tem consequências.', 'text_en_reference' => 'It would be naive to believe this has no consequences.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Uma vez tomada a decisão, não há volta.', 'text_en_reference' => 'Once the decision is made, there is no turning back.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Não deixa de ser irônico que isso tenha acontecido.', 'text_en_reference' => 'It is not without irony that this happened.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'A longo prazo, essa decisão se mostrará acertada.', 'text_en_reference' => 'In the long run, this decision will prove to be right.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ele se empenhou ao máximo para atingir a meta.', 'text_en_reference' => 'He did his utmost to reach the goal.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Poucos sabem que ele dominava cinco idiomas.', 'text_en_reference' => 'Few people know that he was fluent in five languages.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'A análise revela falhas significativas no processo.', 'text_en_reference' => 'The analysis reveals significant flaws in the process.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A complexidade do assunto exige uma reflexão mais profunda.', 'text_en_reference' => 'The complexity of the matter requires deeper reflection.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ela optou por não se manifestar publicamente.', 'text_en_reference' => 'She chose not to speak publicly.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Partindo do pressuposto de que estamos certos, qual o próximo passo?', 'text_en_reference' => 'Assuming we are right, what is the next step?', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A obra desse autor continua relevante até hoje.', 'text_en_reference' => 'This author\'s work remains relevant to this day.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Por mais que eu me esforce, há coisas que fogem ao meu controle.', 'text_en_reference' => 'No matter how hard I try, there are things beyond my control.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Sob nenhuma circunstância essa informação deve ser divulgada.', 'text_en_reference' => 'Under no circumstances should this information be disclosed.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A inovação tecnológica tem transformado a forma como trabalhamos.', 'text_en_reference' => 'Technological innovation has been transforming the way we work.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ele alegou desconhecer os fatos apresentados.', 'text_en_reference' => 'He claimed to be unaware of the facts presented.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A menos que se tomem providências imediatas, o problema se agravará.', 'text_en_reference' => 'Unless immediate action is taken, the problem will worsen.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Cumpre destacar que os resultados superaram as previsões.', 'text_en_reference' => 'It should be noted that the results exceeded the forecasts.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'É válido questionar se essa é a melhor abordagem.', 'text_en_reference' => 'It is worth questioning whether this is the best approach.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Tendo sido avisado com antecedência, ele se preparou adequadamente.', 'text_en_reference' => 'Having been warned in advance, he prepared adequately.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Diante de tantas evidências, não há como discordar.', 'text_en_reference' => 'In the face of so much evidence, there is no way to disagree.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Cada vez mais pessoas estão questionando esse modelo.', 'text_en_reference' => 'More and more people are questioning this model.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ele saiu de mãos vazias, embora tivesse se preparado muito.', 'text_en_reference' => 'He left empty-handed, although he had prepared extensively.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A questão não é se vai acontecer, mas quando.', 'text_en_reference' => 'The question is not if it will happen, but when.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'Contanto que todos cooperem, o resultado será positivo.', 'text_en_reference' => 'Provided that everyone cooperates, the outcome will be positive.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Pouquíssimas vezes na vida eu me senti tão realizado.', 'text_en_reference' => 'Very few times in my life have I felt so fulfilled.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'É preciso que se estabeleçam critérios claros.', 'text_en_reference' => 'It is necessary for clear criteria to be established.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'A reportagem trouxe à tona fatos desconhecidos.', 'text_en_reference' => 'The report brought unknown facts to light.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Não se pode subestimar a importância da educação.', 'text_en_reference' => 'One cannot underestimate the importance of education.', 'level' => 'C1', 'topic' => 'education'],
            ['text_pt' => 'Ele fez valer sua experiência na negociação.', 'text_en_reference' => 'He made his experience count in the negotiation.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Tamanha foi a repercussão que o evento foi adiado.', 'text_en_reference' => 'Such was the repercussion that the event was postponed.', 'level' => 'C1', 'topic' => 'entertainment'],
            ['text_pt' => 'A relação custo-benefício dessa decisão é questionável.', 'text_en_reference' => 'The cost-benefit ratio of this decision is questionable.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'De nada adianta reclamar se não agirmos.', 'text_en_reference' => 'There is no point in complaining if we don\'t take action.', 'level' => 'C1', 'topic' => 'routine'],
            ['text_pt' => 'O sucesso estrondoso do filme surpreendeu até os críticos.', 'text_en_reference' => 'The resounding success of the film surprised even the critics.', 'level' => 'C1', 'topic' => 'entertainment'],
            ['text_pt' => 'Salvo melhor juízo, acredito que essa é a melhor opção.', 'text_en_reference' => 'Unless I am mistaken, I believe this is the best option.', 'level' => 'C1', 'topic' => 'work'],
            ['text_pt' => 'Ele deixou transparecer sua insatisfação durante a reunião.', 'text_en_reference' => 'He let his dissatisfaction show during the meeting.', 'level' => 'C1', 'topic' => 'work'],
        ];

        foreach ($sentences as $sentence) {
            Sentence::updateOrCreate(
                ['text_pt' => $sentence['text_pt']],
                $sentence
            );
        }
    }
}
